[package]
name = "trial_sat"
version = "0.1.0"
edition = "2021"

[dependencies]
num = {package = "num", version = "0.4.3"}
average = {package = "average", path = "submodules/average"}

[profile.dev]
opt-level = 3

[profile.release]
debug = "line-directives-only"
lto = true
panic = "abort"
